name: Health Check

on:
  pull_request:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Perform health check
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" http://35.173.200.10/)
          echo "HTTP Status Code: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "❌ Health check failed!"
            exit 1
          fi
          echo "✅ Health check passed."
      - name: Fail health check
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" http://172.31.81.146/)
          echo "HTTP Status Code: $STATUS_CODE"
          if [ "$STATUS_CODE" -e 200 ]; then
            echo "❌ Health check failed!"
            exit 1
          fi
          echo "✅ Health check passed."
